#!/bin/bash
set -e

cd "animations"
flutter test
cd ..

cd "flutter_maps_firestore"
flutter test
cd ..

cd "infinite_list"
flutter test
cd ..

cd "isolate_example"
flutter test
cd ..

cd "jsonexample"
flutter test
cd ..

cd "place_tracker"
flutter test
cd ..

cd "platform_design"
flutter test
cd ..

cd "platform_view_swift"
flutter test
cd ..

cd "provider_counter"
flutter test
cd ..

cd "provider_shopper"
flutter test
cd ..

cd "shrine"
flutter test
cd ..

cd "veggieseasons"
flutter test
cd ..
