// Copyright 2024 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/cupertino.dart';

// TODO(mit-mit): Update when missing icons are added.
// https://github.com/flutter/flutter/issues/82634
final eventSymbols = <IconData>[
  CupertinoIcons.house_fill,
  CupertinoIcons.ticket_fill,
  CupertinoIcons.gamecontroller_fill,
//CupertinoIcons.theatermasks_fill,
//CupertinoIcons.ladybug_fill,
//CupertinoIcons.books.vertical_fill,
//CupertinoIcons.moon.zzz_fill,
  CupertinoIcons.umbrella_fill,
//CupertinoIcons.paintbrush.pointed_fill,
//CupertinoIcons.leaf_fill,
//CupertinoIcons.globe.americas_fill,
  CupertinoIcons.clock_fill,
//CupertinoIcons.building.2_fill,
  CupertinoIcons.gift_fill,
//CupertinoIcons.graduationcap_fill,
//CupertinoIcons.heart.rectangle_fill,
//CupertinoIcons.phone.bubble.left_fill,
//CupertinoIcons.cloud.rain_fill,
//CupertinoIcons.building.columns_fill,
//CupertinoIcons.mic.circle_fill,
//CupertinoIcons.comb_fill,
//CupertinoIcons.person.3_fill,
  CupertinoIcons.bell_fill,
  CupertinoIcons.hammer_fill,
  CupertinoIcons.star_fill,
//CupertinoIcons.crown_fill,
  CupertinoIcons.briefcase_fill,
//CupertinoIcons.speaker.wave.3_fill,
//CupertinoIcons.tshirt_fill,
  CupertinoIcons.tag_fill,
  CupertinoIcons.airplane,
//CupertinoIcons.pawprint_fill,
//CupertinoIcons.case_fill,
  CupertinoIcons.creditcard_fill,
//CupertinoIcons.infinity.circle_fill,
//CupertinoIcons.dice_fill,
  CupertinoIcons.heart_fill,
  CupertinoIcons.camera_fill,
//CupertinoIcons.bicycle,
//CupertinoIcons.radio_fill,
  CupertinoIcons.car_fill,
  CupertinoIcons.flag_fill,
  CupertinoIcons.map_fill,
//CupertinoIcons.figure.wave,
//CupertinoIcons.mappin.and.ellipse,
//CupertinoIcons.facemask_fill,
  CupertinoIcons.eyeglasses,
  CupertinoIcons.tram_fill,
];
