name: dynamic_theme
description: "Sample app for the google_generative_ai package"
publish_to: 'none'
version: 1.0.0+1
resolution: workspace
environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.0
  url_launcher: ^6.2.6

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

