name: google_maps_in_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.7.0
  http: ^1.0.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/locations.json
