// Autogenerated from Pigeon (v1.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BKBook;
@class BKThumbnail;

@interface BKBook : NSObject
@property(nonatomic, copy, nullable) NSString *title;
@property(nonatomic, copy, nullable) NSString *subtitle;
@property(nonatomic, copy, nullable) NSString *author;
@property(nonatomic, copy, nullable) NSString *summary;
@property(nonatomic, copy, nullable) NSString *publishDate;
@property(nonatomic, strong, nullable) NSNumber *pageCount;
@property(nonatomic, strong, nullable) BKThumbnail *thumbnail;
@end

@interface BKThumbnail : NSObject
@property(nonatomic, copy, nullable) NSString *url;
@end

/// The codec used by BKFlutterBookApi.
NSObject<FlutterMessageCodec> *BKFlutterBookApiGetCodec(void);

@interface BKFlutterBookApi : NSObject
- (instancetype)initWithBinaryMessenger:
    (id<FlutterBinaryMessenger>)binaryMessenger;
- (void)displayBookDetailsBook:(BKBook *)book
                    completion:(void (^)(NSError *_Nullable))completion;
@end
/// The codec used by BKHostBookApi.
NSObject<FlutterMessageCodec> *BKHostBookApiGetCodec(void);

@protocol BKHostBookApi
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)finishEditingBookBook:(BKBook *)book
                        error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BKHostBookApiSetup(id<FlutterBinaryMessenger> binaryMessenger,
                               NSObject<BKHostBookApi> *_Nullable api);

NS_ASSUME_NONNULL_END
