include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - combinators_ordering
    - directives_ordering
    - omit_local_variable_types
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
