# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'ios_content_resizing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_content_resizing

  install_all_flutter_pods(flutter_application_path)

  target 'ios_content_resizingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_content_resizingUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end


