# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Added these two lines for Flutter:
flutter_application_path = '../example_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SimpleIOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleIOSExample
  install_all_flutter_pods(flutter_application_path)

  target 'SimpleIOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleIOSExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
