name: Test iOS Build

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
  workflow_dispatch:

defaults:
  run:
    shell: bash
  
jobs:
  ios-build:
    name: Test flutter beta channel
    runs-on: macos-latest
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: beta
      - run: ./tool/ios_ci_script.sh
