name: Test Android Build

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
  workflow_dispatch:

defaults:
  run:
    shell: bash
  
jobs:
  android-build:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: stable
      - run: ./tool/android_ci_script.sh